# Generated by Django 5.2.6 on 2025-12-22 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_main_project_owner_project'),
        ('task', '0003_alter_task_id_alter_task_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project_main',
        ),
    ]
